version: "3.9"

networks:
  tasker:

services:
  # nginx
  nginx-service:
    image: nginx:1.21.1
    container_name: nginx-container
    ports:
      - 8080:80
    volumes:
      - ./api:/var/www/tasker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - postgres-service
    networks:
      - tasker

  # php
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-container
    ports:
      - 9000:9000
    volumes:
      - ./api:/var/www/tasker
      - ./php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - tasker

  # postgres
  postgres-service:
    image: postgres:13.3
    container_name: postgres-container
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    networks:
      - tasker
    restart: always
    environment:
      - POSTGRES_DB=tasker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # node
  node-service:
    image: node:16.5.0
    container_name: node-container
    volumes:
      - ./client:/var/www/tasker
    working_dir: /var/www/tasker
    networks:
      - tasker
