gesdinet_jwt_refresh_token:
    ttl: 2592000
    token_parameter_name: refresh-token
    single_use: true
    cookie:
        enabled: true
        sameSite: lax
        path: /
        domain: null
        httpOnly: true
        secure: true
