authentication:
    path: /tasker-api/authentication
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /tasker-api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: ['POST']
